-- MySQL Script generated by MySQL Workbench
-- Fri Oct 10 21:52:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BeautyControl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BeautyControl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeautyControl` DEFAULT CHARACTER SET utf8 ;
USE `BeautyControl` ;

-- -----------------------------------------------------
-- Table `BeautyControl`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Countries` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Countries` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Cities` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Cities` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Countries_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cities_Countries_idx` (`Countries_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Countries`
    FOREIGN KEY (`Countries_ID`)
    REFERENCES `BeautyControl`.`Countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Customers` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Customers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Teléfono` VARCHAR(20) NOT NULL,
  `Dirección` VARCHAR(1000) NOT NULL,
  `Fecha de creación` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Cities_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Customers_Cities1_idx` (`Cities_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Cities1`
    FOREIGN KEY (`Cities_ID`)
    REFERENCES `BeautyControl`.`Cities` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Suppliers` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Suppliers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre de proveedor` VARCHAR(150) NOT NULL,
  `Nombre de contacto` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Teléfono` VARCHAR(20) NOT NULL,
  `Countries_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Suppliers_Countries1_idx` (`Countries_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_Countries1`
    FOREIGN KEY (`Countries_ID`)
    REFERENCES `BeautyControl`.`Countries` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Categories` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Categories` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripción` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Products` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Products` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre del producto` VARCHAR(150) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Fecha de creación` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Categories_ID` INT NOT NULL,
  `Suppliers_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Products_Categories1_idx` (`Categories_ID` ASC) VISIBLE,
  INDEX `fk_Products_Suppliers1_idx` (`Suppliers_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`Categories_ID`)
    REFERENCES `BeautyControl`.`Categories` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Suppliers1`
    FOREIGN KEY (`Suppliers_ID`)
    REFERENCES `BeautyControl`.`Suppliers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Warehouses` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Warehouses` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Dirección` VARCHAR(150) NOT NULL,
  `Cities_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Warehouses_Cities1_idx` (`Cities_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouses_Cities1`
    FOREIGN KEY (`Cities_ID`)
    REFERENCES `BeautyControl`.`Cities` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Payments` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Payments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha de pago` DATETIME NOT NULL,
  `Método de  pago` ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA') NOT NULL,
  `Cantidad` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Users` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre de usuario` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Rol` ENUM('cliente', 'empleado', 'admin') NOT NULL,
  `Creado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Actualizado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Estado` ENUM('activo', 'inactivo') NOT NULL,
  `Customers_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Users_Customers1_idx` (`Customers_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Customers1`
    FOREIGN KEY (`Customers_ID`)
    REFERENCES `BeautyControl`.`Customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Employees` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Employees` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Users_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Employees_Users1_idx` (`Users_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Users1`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `BeautyControl`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Shipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Shipments` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Shipments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha de envio` DATETIME NOT NULL,
  `Fecha de entrega` DATETIME NOT NULL,
  `Status` ENUM('EN TRANSITO', 'ENTREGADO', 'RETRASADO') NOT NULL,
  `Warehouses_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Shipments_Warehouses1_idx` (`Warehouses_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Shipments_Warehouses1`
    FOREIGN KEY (`Warehouses_ID`)
    REFERENCES `BeautyControl`.`Warehouses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Ordenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Ordenes` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Ordenes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Fecha de la orden` DATETIME NOT NULL,
  `Status` ENUM('PENDIENTE', 'ENVIADO', 'ENTREGADO', 'REGRESADO') NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `Payments_ID` INT NOT NULL,
  `Customers_ID` INT NOT NULL,
  `Employees_ID` INT NOT NULL,
  `Shipments_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Ordenes_Payments1_idx` (`Payments_ID` ASC) VISIBLE,
  INDEX `fk_Ordenes_Customers1_idx` (`Customers_ID` ASC) VISIBLE,
  INDEX `fk_Ordenes_Employees1_idx` (`Employees_ID` ASC) VISIBLE,
  INDEX `fk_Ordenes_Shipments1_idx` (`Shipments_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ordenes_Payments1`
    FOREIGN KEY (`Payments_ID`)
    REFERENCES `BeautyControl`.`Payments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordenes_Customers1`
    FOREIGN KEY (`Customers_ID`)
    REFERENCES `BeautyControl`.`Customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordenes_Employees1`
    FOREIGN KEY (`Employees_ID`)
    REFERENCES `BeautyControl`.`Employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordenes_Shipments1`
    FOREIGN KEY (`Shipments_ID`)
    REFERENCES `BeautyControl`.`Shipments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Devoluciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Devoluciones` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Devoluciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Razón` VARCHAR(500) NOT NULL,
  `Fecha de devolución` DATETIME NOT NULL,
  `Cantidad de reembolso` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`Order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`Order_items` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`Order_items` (
  `Products_ID` INT NOT NULL,
  `Ordenes_ID` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio por unidad` DECIMAL(10,2) NOT NULL,
  `Devoluciones_ID` INT NOT NULL,
  PRIMARY KEY (`Products_ID`, `Ordenes_ID`),
  INDEX `fk_Products_has_Ordenes_Ordenes1_idx` (`Ordenes_ID` ASC) VISIBLE,
  INDEX `fk_Products_has_Ordenes_Products1_idx` (`Products_ID` ASC) VISIBLE,
  INDEX `fk_Order_items_Devoluciones1_idx` (`Devoluciones_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Ordenes_Products1`
    FOREIGN KEY (`Products_ID`)
    REFERENCES `BeautyControl`.`Products` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Ordenes_Ordenes1`
    FOREIGN KEY (`Ordenes_ID`)
    REFERENCES `BeautyControl`.`Ordenes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_items_Devoluciones1`
    FOREIGN KEY (`Devoluciones_ID`)
    REFERENCES `BeautyControl`.`Devoluciones` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeautyControl`.`inventory_movements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeautyControl`.`inventory_movements` ;

CREATE TABLE IF NOT EXISTS `BeautyControl`.`inventory_movements` (
  `Products_ID` INT NOT NULL,
  `Warehouses_ID` INT NOT NULL,
  `Cantidad` VARCHAR(45) NOT NULL,
  `Tipo de movimiento` ENUM('IN', 'OUT') NOT NULL,
  `Fecha del movimiento` DATETIME NOT NULL,
  INDEX `fk_Products_has_Warehouses_Warehouses1_idx` (`Warehouses_ID` ASC) VISIBLE,
  INDEX `fk_Products_has_Warehouses_Products1_idx` (`Products_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Warehouses_Products1`
    FOREIGN KEY (`Products_ID`)
    REFERENCES `BeautyControl`.`Products` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Warehouses_Warehouses1`
    FOREIGN KEY (`Warehouses_ID`)
    REFERENCES `BeautyControl`.`Warehouses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
